site_name: udesa-pc
site_url: https://pc.udesa.edu.ar/

theme:
  name: material


extra_javascript:
  - javascripts/mathjax.js
  - javascripts/fontawesome/all.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Instalación: 
    - Mac: installation/mac-install.md
    - Windows: installation/windows-install.md

  - Setup:
    - Editor: setup/vs-code.md
    - Nuevo Proyecto: setup/new_project.md

  - Recursion:
    - Introducción: recursion/intro.md
  
  - OOP:
    - Introducción: oop/intro.md
    - Ejemplo de un objeto: oop/disect_objects.md

  - Proyectos:
    - Recomendador: projects/song-recommendation.md
