site_name: udesa-pc
site_url: https://pc.udesa.edu.ar/

theme:
  name: material


markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Instalación: 
    - Mac: installation/mac-install.md
    - Windows: installation/windows-install.md