site_name: udesa-pc
site_url: https://pc.udesa.edu.ar/

theme:
  name: material


markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Instalación: 
    - Mac: installation/mac-install.md
    - Windows: installation/windows-install.md

  - Setup:
    - Editor: setup/vs-code.md
    - Nuevo Proyecto: setup/new_project.md